enviromentName= " Terraform-tutorial-"
InstanceType="t2.medium"
AmiID= "ami-052efd3df9dad4825"
CPUPolicyTargetValue=30
MinCapacity="2"
MaxCapacity="4"
DesiredCapacity="2"
keyPair= "keyforuda"
bucketname= "terraform-web-code-bucket224424345"